### PR TITLE
Normalize header files. Phase 1

### PR DESCRIPTION
**Pull request by dsuponitskiy**

### CODE REVIEW

**Comment by dsuponitskiy** [comment]
Work done for this ticket:
1. Created forward declarations files for different classes ("<original_header_name>-fwd.h"). They can be included instead of complete class definitions.
2. Removed unnecessary header files' includes.
3. The PlaintextEncodings enumerations were moved from plaintext.h to constants.h. Their names were capitalized and slightly changed for better readability.
4. Made enum PtxtPolyType a part of PlaintextImpl as this enum is not used anywhere else
5. Moved code/function implementations from header to source files to avoid additional includes.
6. Moved the MetadataTest class to pke/unittests/utils as it is meant for unit testing only
7. Created a separate file for the EncryptResult/DecryptResult structs
8. Created a new function CryptoContextFactory<Element>::GetFullContextByDeserializedContext() to avoid including cryptocontext.h
9. Completely removed the following files: bfvrns-advancedshe.cpp, bfvrns-pre.cpp, bfvrns-fhe.cpp, keyswitch-rns.cpp, bgvrns-pre.cpp, bgvrns-advancedshe.cpp, bgvrns-fhe.cpp
, plaintextfactory.cpp, ckksrns-pke.cpp, ckksrns-pre.cpp, rlwe-cryptoparameters.cpp, rns-advancedshe.cpp, rns-fhe.cpp, rns-pre.cpp, rns-scheme.cpp, allscheme.h, allkey.h, allbfvrns.h, allbase.h, allrns.h

**Review by jbates-duality — COMMENTED** [review]
commit 1: #include changes, nix of allscheme.h where possible, creation of a new file EncryptResult object.

**Review by jbates-duality — COMMENTED** [review]
Commit 3: More specificity on encodingType [INVALID_ENCODING, PACKED_ENCODING, etc].  Moving of small hunks of code into cpp files to decouple.

**Review by jbates-duality — COMMENTED** [review]
Commit 4: More de-coupling with forward-declaration header files.  Metadata de-inline to decouple.  Metadata unit test added.

**Review by jbates-duality — APPROVED** [review]
I have taken a second pass through these commits, and have run all unit tests from a default build.  No build issue.  No unit test issue.  I am approving now.

**Pull request merged**
