### PR TITLE
Updated OpenFHE with the latest bugfixes from Palisade

### PR DESCRIPTION
**Pull request by dsuponitskiy**

### CODE REVIEW

**Comment by dsuponitskiy** [comment]
Closes #149:
https://gitlab.com/palisade/palisade-development/-/merge_requests/387 - Ian
https://gitlab.com/palisade/palisade-development/-/merge_requests/388 - Ian
https://gitlab.com/palisade/palisade-development/-/merge_requests/389 - Ian
https://gitlab.com/palisade/palisade-development/-/merge_requests/393 - Nick
https://gitlab.com/palisade/palisade-development/-/merge_requests/394 - Matt

**Comment by dsuponitskiy** [comment]
manually started 4 CI jobs.

**Review by iquah1 — APPROVED** [review]
LGTM consolidation of multiple PRs

**Review by mtriplett-duality — COMMENTED** [review]
The stuff I know looks good, the deeper changes I don't have context for so I can't say

**Review by mtriplett-duality — APPROVED** [review]

**Pull request merged**
