### PR TITLE
Address internal review

### PR DESCRIPTION
**Pull request by iquah1**

### CODE REVIEW

**Review by jbates-duality — APPROVED** [review]
This PR is all documentation, and upon consultation with IQ, I am approving and merging.

**Review by dsuponitskiy — APPROVED** [review]
The changes look good to me.

**Comment by dsuponitskiy** [comment]
Restarted the pipeline

**Comment by jbates-duality** [comment]
I see that CI has completed on this patch.  I have already approved.  I'm going to squash and merge now.

**Pull request merged**
