### PR TITLE
Removal of src/core/include/utils/defines.h

### PR DESCRIPTION
**Pull request by dsuponitskiy**

### CODE REVIEW

**Comment by dsuponitskiy** [comment]
All 4 CI jobs succeeded.

**Comment by jbates-duality** [comment]
As part of investigating the removal of OPENFHE_UNUSED(), I ran all benchmarks at tip of dev, and at tip of this branch, and observed that the differential in run times looked like just noise.  i.e. this is not short-circuiting things.  ...in the benchmarks, at least.  Additionally, CI ran and all unit tests are passing.  I will also attach my code review comments.

**Comment by jbates-duality** [comment]
I have a feeling that this will have borked the HEXL build.  I have HEXL pinned to the last release, so I'm not going to let that get in the way of this PR.  I will attend to any HEXL issues after the next OpenFHE release.

**Review by jbates-duality — APPROVED** [review]
Fairly straightforward patch to remove an ugly little include file.  Doesn't look like anything troublesome here, and CI ran.  See my other comments.  Approving.

**Comment by dsuponitskiy** [comment]
closes #155

**Pull request merged**
